(function () {
  "use strict";

  // ---------------------------------------------------------------------
  // 5x7 pixel font. Each character is 7 rows of 5 bits (1 = filled block).
  // Only covers what a Linux hostname can contain: A-Z, 0-9, and hyphen.
  // ---------------------------------------------------------------------
  var FONT = {
    A: ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    B: ["11110", "10001", "10001", "11110", "10001", "10001", "11110"],
    C: ["01111", "10000", "10000", "10000", "10000", "10000", "01111"],
    D: ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
    E: ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    F: ["11111", "10000", "10000", "11110", "10000", "10000", "10000"],
    G: ["01111", "10000", "10000", "10011", "10001", "10001", "01111"],
    H: ["10001", "10001", "10001", "11111", "10001", "10001", "10001"],
    I: ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
    J: ["00111", "00010", "00010", "00010", "00010", "10010", "01100"],
    K: ["10001", "10010", "10100", "11000", "10100", "10010", "10001"],
    L: ["10000", "10000", "10000", "10000", "10000", "10000", "11111"],
    M: ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
    N: ["10001", "11001", "10101", "10101", "10011", "10001", "10001"],
    O: ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    P: ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    Q: ["01110", "10001", "10001", "10001", "10101", "10010", "01101"],
    R: ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    S: ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    T: ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    U: ["10001", "10001", "10001", "10001", "10001", "10001", "01110"],
    V: ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    W: ["10001", "10001", "10001", "10101", "10101", "10101", "01010"],
    X: ["10001", "10001", "01010", "00100", "01010", "10001", "10001"],
    Y: ["10001", "10001", "01010", "00100", "00100", "00100", "00100"],
    Z: ["11111", "00001", "00010", "00100", "01000", "10000", "11111"],
    "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    "3": ["11111", "00010", "00100", "00010", "00001", "10001", "01110"],
    "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    "5": ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
    "6": ["00110", "01000", "10000", "11110", "10001", "10001", "01110"],
    "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
    "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
    "9": ["01110", "10001", "10001", "01111", "00001", "00010", "01100"],
    "-": ["00000", "00000", "00000", "11111", "00000", "00000", "00000"]
  };

  var CHAR_COLS = 5;
  var CHAR_ROWS = 7;
  var LETTER_GAP_COLS = 1;

  // ---------------------------------------------------------------------
  // Resolve the hostname. config.js (generated by the container's
  // entrypoint script at startup) sets window.APP_CONFIG.hostname.
  // If it's missing, for example when opening this file directly without
  // the Docker container, fall back to a placeholder so the game still runs.
  // ---------------------------------------------------------------------
  var rawHostname =
    (window.APP_CONFIG && window.APP_CONFIG.hostname) || "UNKNOWN";
  var hostname = rawHostname.toUpperCase();

  // Strip any character that has no glyph in the font, just in case.
  var hostnameChars = [];
  for (var i = 0; i < hostname.length; i++) {
    if (FONT[hostname[i]]) {
      hostnameChars.push(hostname[i]);
    }
  }
  if (hostnameChars.length === 0) {
    hostnameChars = ["U", "N", "K", "N", "O", "W", "N"];
  }

  document.getElementById("hostnameLabel").textContent = hostnameChars.join("");

  // ---------------------------------------------------------------------
  // Canvas + layout sizing
  // Block size shrinks so the full hostname always fits on a single row,
  // but never gets so small it becomes unreadable, and never grows so
  // large that a short hostname looks absurd.
  // ---------------------------------------------------------------------
  var canvas = document.getElementById("game");
  var ctx = canvas.getContext("2d");

  var BASE_WIDTH = 800;
  var BASE_HEIGHT = 560;
  var MARGIN_X = 40;
  var WALL_TOP = 50;

  var totalCols =
    hostnameChars.length * (CHAR_COLS + LETTER_GAP_COLS) - LETTER_GAP_COLS;

  var usableWidth = BASE_WIDTH - MARGIN_X * 2;
  var blockSize = Math.floor(usableWidth / totalCols);
  blockSize = Math.max(6, Math.min(26, blockSize));

  var wallWidth = totalCols * blockSize;
  var canvasWidth = Math.max(BASE_WIDTH, wallWidth + MARGIN_X * 2);
  var canvasHeight = BASE_HEIGHT;

  canvas.width = canvasWidth;
  canvas.height = canvasHeight;

  var wallStartX = Math.floor((canvasWidth - wallWidth) / 2);

  // ---------------------------------------------------------------------
  // Build bricks from the font bitmap
  // ---------------------------------------------------------------------
  var LETTER_COLORS = [
    "#00e5ff",
    "#5cf1ff",
    "#00b8d9",
    "#7df9ff",
    "#00e5ff",
    "#5cf1ff",
    "#00b8d9"
  ];

  function buildBricks() {
    var bricks = [];
    var colCursor = 0;

    for (var ci = 0; ci < hostnameChars.length; ci++) {
      var glyph = FONT[hostnameChars[ci]];
      var color = LETTER_COLORS[ci % LETTER_COLORS.length];

      for (var row = 0; row < CHAR_ROWS; row++) {
        for (var col = 0; col < CHAR_COLS; col++) {
          if (glyph[row][col] === "1") {
            bricks.push({
              x: wallStartX + (colCursor + col) * blockSize,
              y: WALL_TOP + row * blockSize,
              w: blockSize - 1,
              h: blockSize - 1,
              alive: true,
              color: color
            });
          }
        }
      }
      colCursor += CHAR_COLS + LETTER_GAP_COLS;
    }
    return bricks;
  }

  var bricks = buildBricks();

  // ---------------------------------------------------------------------
  // Paddle, ball, and general game state
  // ---------------------------------------------------------------------
  var paddle = {
    w: Math.max(70, Math.min(120, canvasWidth * 0.12)),
    h: 12,
    x: canvasWidth / 2 - 50,
    y: canvasHeight - 34,
    speed: 7
  };

  var ball = {
    radius: 7,
    x: canvasWidth / 2,
    y: paddle.y - 20,
    vx: 4,
    vy: -4
  };

  var lives = 3;
  var gameState = "playing"; // playing | won | lost
  var keys = { left: false, right: false };

  var livesDisplay = document.getElementById("livesDisplay");
  var overlay = document.getElementById("overlay");
  var overlayTitle = document.getElementById("overlayTitle");
  var restartBtn = document.getElementById("restartBtn");

  function resetBall() {
    ball.x = canvasWidth / 2;
    ball.y = paddle.y - 20;
    var direction = Math.random() < 0.5 ? -1 : 1;
    ball.vx = 4 * direction;
    ball.vy = -4;
    paddle.x = canvasWidth / 2 - paddle.w / 2;
  }

  function updateLivesDisplay() {
    livesDisplay.textContent = "Lives: " + lives;
  }

  function showOverlay(title) {
    overlayTitle.textContent = title;
    overlay.classList.remove("hidden");
  }

  function hideOverlay() {
    overlay.classList.add("hidden");
  }

  function restartGame() {
    bricks = buildBricks();
    lives = 3;
    gameState = "playing";
    updateLivesDisplay();
    hideOverlay();
    resetBall();
  }

  restartBtn.addEventListener("click", restartGame);

  // ---------------------------------------------------------------------
  // Input handling: keyboard (arrow keys and A/D) and mouse
  // ---------------------------------------------------------------------
  document.addEventListener("keydown", function (e) {
    if (e.key === "ArrowLeft" || e.key === "a" || e.key === "A") {
      keys.left = true;
    }
    if (e.key === "ArrowRight" || e.key === "d" || e.key === "D") {
      keys.right = true;
    }
  });

  document.addEventListener("keyup", function (e) {
    if (e.key === "ArrowLeft" || e.key === "a" || e.key === "A") {
      keys.left = false;
    }
    if (e.key === "ArrowRight" || e.key === "d" || e.key === "D") {
      keys.right = false;
    }
  });

  canvas.addEventListener("mousemove", function (e) {
    var rect = canvas.getBoundingClientRect();
    var scaleX = canvas.width / rect.width;
    var mouseX = (e.clientX - rect.left) * scaleX;
    paddle.x = mouseX - paddle.w / 2;
  });

  // ---------------------------------------------------------------------
  // Update loop
  // ---------------------------------------------------------------------
  function update() {
    if (gameState !== "playing") {
      return;
    }

    if (keys.left) {
      paddle.x -= paddle.speed;
    }
    if (keys.right) {
      paddle.x += paddle.speed;
    }
    paddle.x = Math.max(0, Math.min(canvasWidth - paddle.w, paddle.x));

    ball.x += ball.vx;
    ball.y += ball.vy;

    // Wall collisions
    if (ball.x - ball.radius < 0) {
      ball.x = ball.radius;
      ball.vx *= -1;
    }
    if (ball.x + ball.radius > canvasWidth) {
      ball.x = canvasWidth - ball.radius;
      ball.vx *= -1;
    }
    if (ball.y - ball.radius < 0) {
      ball.y = ball.radius;
      ball.vy *= -1;
    }

    // Paddle collision
    if (
      ball.y + ball.radius >= paddle.y &&
      ball.y + ball.radius <= paddle.y + paddle.h &&
      ball.x >= paddle.x &&
      ball.x <= paddle.x + paddle.w &&
      ball.vy > 0
    ) {
      var hitPos = (ball.x - paddle.x) / paddle.w; // 0 (left edge) to 1 (right edge)
      var angle = (hitPos - 0.5) * (Math.PI / 3); // max +/- 60 degrees
      var speed = Math.sqrt(ball.vx * ball.vx + ball.vy * ball.vy);
      ball.vx = speed * Math.sin(angle);
      ball.vy = -Math.abs(speed * Math.cos(angle));
    }

    // Brick collisions
    for (var i = 0; i < bricks.length; i++) {
      var b = bricks[i];
      if (!b.alive) continue;

      if (
        ball.x + ball.radius > b.x &&
        ball.x - ball.radius < b.x + b.w &&
        ball.y + ball.radius > b.y &&
        ball.y - ball.radius < b.y + b.h
      ) {
        b.alive = false;
        ball.vy *= -1;
        break;
      }
    }

    // Ball missed
    if (ball.y - ball.radius > canvasHeight) {
      lives -= 1;
      updateLivesDisplay();
      if (lives <= 0) {
        gameState = "lost";
        showOverlay("GAME OVER");
      } else {
        resetBall();
      }
    }

    // Win condition
    var remaining = bricks.filter(function (b) {
      return b.alive;
    }).length;
    if (remaining === 0) {
      gameState = "won";
      showOverlay("WALL CLEARED");
    }
  }

  // ---------------------------------------------------------------------
  // Draw loop
  // ---------------------------------------------------------------------
  function draw() {
    ctx.clearRect(0, 0, canvasWidth, canvasHeight);

    ctx.fillStyle = "#0b0f14";
    ctx.fillRect(0, 0, canvasWidth, canvasHeight);

    // Bricks
    for (var i = 0; i < bricks.length; i++) {
      var b = bricks[i];
      if (!b.alive) continue;
      ctx.fillStyle = b.color;
      ctx.fillRect(b.x, b.y, b.w, b.h);
    }

    // Paddle
    ctx.fillStyle = "#e6f1f5";
    ctx.fillRect(paddle.x, paddle.y, paddle.w, paddle.h);

    // Ball
    ctx.beginPath();
    ctx.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2);
    ctx.fillStyle = "#ffffff";
    ctx.fill();
    ctx.closePath();
  }

  function loop() {
    update();
    draw();
    requestAnimationFrame(loop);
  }

  updateLivesDisplay();
  resetBall();
  loop();
})();
